### ISSUE TITLE
No support for object injection & multiple environment?

### ISSUE THREAD

**Issue by apryiomka** [autofac/Autofac.Configuration#15]
I cannot see neither in documentation nor in code support for keyed injection in the JSON configuration. For instance:
`
"properties": {
      "DictionaryProp": {
        "key": "value"
      },
      "ListProp": [1, 2, 3, 4, 5]
    }
`
You can only inject scalar values like strings, integers, etc or lists of strings / integers or dictionaries of strings / integers (as values). But what about injecting other services by key, i am looking for syntax something like:
`
"parameters": {
      "repository": { "key": "baseRepository" }
    }
`
Also, what about different environments. I can have one value for one environment, another value for another environment:
`
{
  "components": [{
    "type": "Autofac.Example.SqlRepository, Autofac.Example",
    "services": [{
      "type": "Autofac.Example.ISqlRepository"
    }, {
      "type": "Autofac.Example.IRepository",
      "key": "baseRepository"
    }],
    "parameters": {
      "connectionString": "connection string for dev environment"
    }
  }]
}
`
No, how do i provide connection string for staging environment or for production environment without redefining the whole config?

Other frameworks such as Spring.NET allow import of other config files within the config files as well where you can provide "overwrites" for some properties.

**Comment by tillig** [comment]
There are a couple of questions here, so I'll answer each in turn:

**How do I inject keyed services via configuration?**
The short version is, you don't. Configuration is not meant to be a feature-for-feature replacement for the programmatic interface. The way to handle this is to [create an Autofac module](http://autofac.readthedocs.io/en/latest/configuration/modules.html) with the keyed service setup (or other more complex thing) and use the JSON/XML configuration to optionally register that module.

**How do I handle different environments?**
The [Microsoft.Extensions.Configuration](https://github.com/aspnet/Configuration) system is very flexible and does allow for overwrites/additions of configuration settings. We interface with that specifically because it handles all that work for us. The way this is commonly handled, for example in ASP.NET Core, is to register a base configuration that is applicable to all environments and then register an additional, optional configuration file based on environment.

```csharp
    public Startup(IHostingEnvironment env)
    {
        var builder = new ConfigurationBuilder()
            .SetBasePath(env.ContentRootPath)
            .AddJsonFile("autofac.json", optional: true)
            .AddJsonFile($"autofac.{env.EnvironmentName}.json", optional: true)
            .AddEnvironmentVariables();
       var autofacConfiguration = builder.Build();
    }
```

In this case, `autofac.json` would have your common configuration, and you would have files like `autofac.Development.json` or `autofac.Production.json` to load based on the environment name. How you determine the environment really is app specific, but that should give you an idea.

I'd recommend you check out [the Microsoft.Extensions.Configuration repo](https://github.com/aspnet/Configuration) and looking at their examples / linked articles for more info on the great stuff they offer.
