### ISSUE TITLE
How To User Xml Configuation in Winform Framework 4.5

### ISSUE THREAD

**Issue by exy3351** [autofac/Autofac.Configuration#24]
Hello 
你好，请问一下在Winform（使用.net framework 4.5）中如何使用 xml配置文件？最新的Autofac.Configuration好像不在支持了，现在都不知道该如何在winform使用Autofac.Configuration了

**Comment by exy3351** [comment]
> Hello
> 你好，请问一下在Winform（使用.net framework 4.5）中如何使用 xml配置文件？最新的Autofac.Configuration好像不在支持了，现在都不知道该如何在winform使用Autofac.Configuration了

**Comment by tillig** [comment]
I recommend [reading the documentation](https://autofac.readthedocs.io/en/latest/configuration/xml.html) as config has changed a lot since Autofac v 4.0. There is no specific guidance for individual app types.

If you have additional usage questions please post to StackOverflow and tag the question with `autofac`.
