### ISSUE TITLE
Typed parameter string to char. Unable to convert object of type 'System.String' to type 'System.Char[]'

### ISSUE THREAD

**Issue by nshCore** [autofac/Autofac.Configuration#25]
I have a class ctor with a char[] for the parameter

` public Engine(char[] passphrase)
`
which I am trying to register in my config like

```
    {
      "type": "Some.Engine, Some.Engine",
      "services": [
        {
          "type": "Some.IEngine, Some.Engine"
        }
      ],
      "parameters": {
        "passphrase": "mypassword`1[[System.Char[], mscorlib]]"
      }
    },
```

Which fails with the following exception

> System.InvalidOperationException: Unable to convert object of type 'System.String' to type 'System.Char[]'.
>    at Autofac.Configuration.Util.TypeManipulation.ChangeToCompatibleType(Object value, Type destinationType, TypeConverterAttribute converterAttribute) in C:\projects\autofac-configuration\src\Autofac.Configuration\Util\TypeManipulation.cs:line 164

Is it not possible to type the string to a char[] or am I missing something

**Comment by tillig** [comment]
While you can use an indexer into a string to get individual characters, a string is, itself, not actually just a `char[]`. You can explicitly convert a string using the `System.String.ToCharArray()` method, but the default `TypeConverter` for strings, `System.ComponentModel.StringConverter` does not know how to convert a string to a `char[]` and you can't simply cast.

You can verify this with a tiny block of code:

```c#
var x = "test";
var y = (char[])x;
```

This won't compile. You'll get a `CS0030` error because you can't cast `string` to `char[]`.
