### ISSUE TITLE
RegisterModule does not work properly on net5

### ISSUE THREAD

**Issue by exy3351** [autofac/Autofac.Configuration#36]
When using json configuration file injection, autofac throws an exception

at Autofac.Configuration.Core.ConfigurationExtensions.GetType(IConfiguration configuration, String key, Assembly defaultAssembly)
   at Autofac.Configuration.Core.ComponentRegistrar.RegisterConfiguredComponents(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.Core.ConfigurationRegistrar.RegisterConfiguration(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.ConfigurationModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)

See the attachment for the demo reproduced

[AutofacDemo.zip](https://github.com/autofac/Autofac/files/6040758/AutofacDemo.zip)

**Comment by tillig** [comment]
It took me a bit to get this demo working. I'm on a Mac, so trying to reproduce it in a Windows Forms app isn't really a thing.

Instead, I created a .NET Core console app that used your container logic:

```c#
using System;
using DemoCore;

namespace DemoConsole
{
    class Program
    {
        static void Main(string[] args)
        {
            var fac = new AutofacContainer();
            try
            {
                var p = $@"/Users/tillig/Downloads/AutofacDemo/Debug/Autofac.json";
                fac.RegisterConfig(p);
                fac.Build();

                var demo = fac.Resolve<IDemo>();
                var value = demo?.GetValue();
                Console.WriteLine(value);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
            }
        }
    }
}
```

The first challenge I ran into was that using a common `OutputPath` of `../Debug/` and all that... didn't really get all the assemblies in the right spot. Doing that, I got an exception that `DemoLib` couldn't be found.

**You didn't actually include the exception message here, just the stack trace** so it's not actually possible to see _what_ the problem was when you tried it, just _where_ it was.

To solve the assembly loading issue, I added a reference to the `DemoLib` project from the console app. I recognize what you're likely trying to do is something with plugins, hence the output paths and copy, but stick with me: Once I added that reference... **It worked like a charm.** Configuration worked, it properly loaded the plugin, it output `This is Demo1` to the console.

What that means to me is that the problem here is _very likely_ with how you're packaging the application and trying to load assemblies. That is, using a common output folder, etc. and assuming the application loads everything in the folder into the application domain.

I can't speak for .NET 5 Windows Forms, but I do know that, in general, doing plugins in the new non-desktop-framework .NET world is a lot harder than it was before. It's not just drop in an assembly and go. There's working with [`AssemblyLoadContext` to help locate things](https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/loading-managed)

Autofac is not responsible for doing the plugin assembly loading. That's up to the .NET runtime and your app to handle. If it's loaded we can register it; if not, there's nothing Autofac is going to do to correct the issue.

I'm going to close this for now, since once the assembly loading part is fixed it does seem to work and I can't reproduce the issue. If you can create a possibly simpler repro (e.g., not Windows forms?) and show the issue isn't with assembly loading, we can dive in again.

**Comment by tillig** [comment]
I noticed a duplicate issue filed with the exception message:

> The type 'DemoLib.Demo1, DemoLib' could not be found. It may require assembly qualification, e.g. "MyType,
MyAssembly".

This message indicates exactly what I'm talking about - the configuration is correct but the assembly isn't loaded. Figuring out how to load the assembly isn't something Autofac can fix for you. If the assembly CAN be loaded, The configuration will work.
