### ISSUE TITLE
Problems when when using Autofac.Configuration in .NET 5.0.6 class library via C++\CLI wrapper

### ISSUE THREAD

**Issue by bairog** [autofac/Autofac.Configuration#38]
I have a solution with the following structure:

- **NET5ClassLibraryInterface** - .NET 5.0.6 class library with **net5.0-windows TFM**. Refefences latest [**Autofac.Configuration 6.0.0**](https://www.nuget.org/packages/autofac.configuration) and [**Microsoft.Extensions.Configuration.Json 5.0.0**](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/5.0.0) nuget packages. Contains `IDataCreate` interface and a static class that calls functions from that interface (uses `container.Resolve<IDataCreate>()`). Compiled as **x86**. Also contains **config.json**:
```
{
  "components": [
    {
      "type": "NET5ClassLibraryImplementation.DataCreate, NET5ClassLibraryImplementation",
      "services": [
        {
          "type": "NET5ClassLibraryInterface.IDataCreate, NET5ClassLibraryInterface"
        }
      ]
    }
  ]
}
```
- **NET5ClassLibraryImplementation** (references **NET5ClassLibraryInterface**) - .NET 5.0.6 class library with **net5.0-windows TFM** - contains `DataCreate` class that implements `IDataCreate` interface. Compiled as **x86**.
- **NET5ClassLibraryTest** (references **NET5ClassLibraryInterface**) - .NET 5.0.6 console application with **net5.0-windows TFM** - calls functions from **NET5ClassLibraryInterface** static class. Compiled as **x86**. **Works with no problem!!!.**
- **NET5ClassLibraryInterop** (references **NET5ClassLibraryInterface**) - .NET 5.0.6 C++\CLI wrapper. Compiled  as **x86, Multi-byte Character Set, wchar_t-**.
- **NET5ClassLibraryInteropTest** - C++ console test application. Compiled  as **x86, Multi-byte Character Set, wchar_t-**.

When I run **NET5ClassLibraryInteropTest** line `var container = builder.Build();` throws an exception:
> System.TypeInitializationException: ''The type initializer for 'NET5ClassLibraryInterface.Class1' threw an exception.'
> Inner exception: 'ArgumenException: "The type 'NET5ClassLibraryImplementation.DataCreate' is not assignable to service 'NET5ClassLibraryInterface.IDataCreate'."

## Describe the Bug
Interface `NET5ClassLibraryInterface.IDataCreate` is not resolving into `NET5ClassLibraryImplementation.DataCreate` - exception.

## Steps to Reproduce
Sample repo - https://github.com/bairog/NET5ClassLibraryWithAutofacInteropTest
Compile it (for some reason you need to compile twice for compiling **NET5ClassLibraryInteropTest** project) and start debugging **NET5ClassLibraryInterface** project (it starts **NET5ClassLibraryInteropTest** in project Debug settings)

## Expected Behavior
Interface `NET5ClassLibraryInterface.IDataCreate` resolves into `NET5ClassLibraryImplementation.DataCreate`.

## Exception with Stack Trace
```text
System.TypeInitializationException: ''The type initializer for 'NET5ClassLibraryInterface.Class1' threw an exception.'
Inner exception: 'ArgumenException: "The type 'NET5ClassLibraryImplementation.DataCreate' is not assignable to service 'NET5ClassLibraryInterface.IDataCreate'."

Stack trace: "   at NET5ClassLibraryInterface.Class1.GetInt() in D:\NET5ClassLibraryWithAutofacInteropTest\NET5ClassLibraryInterface\Class1.cs:line 55
   at NET5ClassLibraryInterop.NET5nterop.GetInt() in D:\NET5ClassLibraryWithAutofacInteropTest\NET5ClassLibraryInterop\NET5ClassLibraryInterop.cpp:line 7"
```

## Dependency Versions
Autofac: 
[**Autofac.Configuration**](https://www.nuget.org/packages/autofac.configuration) 6.0.0
 [**Microsoft.Extensions.Configuration.Json**](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/5.0.0) 5.0.0

## Additional Info
Target framework: .NET 5.0.6
Operating system: Windows 10 x64 1909
IDE: Visual Studio 2019 16.10.0 REL Community

**Comment by tillig** [comment]
Based on the linked issue I'm not convinced there's really anything here that Autofac can do to fix it. Autofac does do [`Assembly.Load` based on the assembly name you provide](https://github.com/autofac/Autofac.Configuration/blob/ec1c6438ceb3f3338c7364e35e7303f014e3fc39/src/Autofac.Configuration/Core/ConfigurationExtensions.cs#L84) and it [does `Type.GetType` with the name you provide](https://github.com/autofac/Autofac.Configuration/blob/ec1c6438ceb3f3338c7364e35e7303f014e3fc39/src/Autofac.Configuration/Core/ConfigurationExtensions.cs#L213), but we don't have any influence over ensuring the indirection through C++ wrappers will work abs there's nothing we do about customizing assembly load contexts.

If you have a _specific suggestion_ on something we can do, we're open to it, but it sounds like there may be something larger/unrelated going on outside our control.

I'll leave this open for a bit and wait to hear back; if we don't hear back or if this was just an FYI, we can close it. If it gets closer and something comes up later, we can always reopen.

**Comment by bairog** [comment]
> Based on the linked issue I'm not convinced there's really anything here that Autofac can do to fix it

So my project setup (`config.json` file, `Autofac.Configuration` library usage, etc.) is correct? 
And you are 100% sure that the core of the problem is in C++/CLI mechanism itself?

**Comment by bairog** [comment]
@tillig BTW in the linked issue ("pure" C# without any IoC containers -> C++/CLI-> C++) there is a workaround: maually adding the following line to **NET5ClassLibraryInterop.vcxproj**
```
<ItemGroup>
    <FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
</ItemGroup>
```
It solves the problem for the linked issue but in this particular issue - it changes nothing. 
So I doubt that the core of problem belongs exclusively to the C++/CLI technology itself.

**Comment by tillig** [comment]
Here's what I know:

- In applications using the current configuration with assembly qualified type names, configuration works.
- We have [a working example proving that it works](https://github.com/autofac/Examples/blob/master/src/ConfigurationExample/autofac.json).
- We do not have any use cases or examples showing C++ interop wrappers.

**You should try to get configuration working _without_ the C++ wrapper** to verify your settings and then fight the extra stuff. While I'm more than happy to help, this isn't my paid gig and I don't really have time to be a consulting and debugging service. Am I sure your config is right? I can't guarantee it but I quickly eyeballed it and it seemed OK. The way you can verify it is by removing the extra C++ part from your repro and just getting straight .NET working.

The exception message about one type not being castable to another type indicates to me that both types got loaded, so from a config standpoint, the types _were found and registered_ so there's something else amiss.

I will note, we just recently had a person doing assembly loading on the fly to try to decouple things [and there was an assembly load context problem](https://github.com/autofac/Autofac/issues/1277) such that the assembly was being loaded into the application in two different contexts, resulting in the same assembly being in the application twice, with the same types declared twice, but they _weren't literally the same thing_ because of the two different contexts. I don't know if that's related here, but I scanned through your example and did see some assembly loading/handling code, so that might be an avenue to investigate.

**Comment by tillig** [comment]
Given there's nothing here that Autofac can do differently, I'm going to close this. If it turns out a solution is found, we'd be happy to accept a PR with the fix.
