### ISSUE TITLE
Update QuickStarted to show .NET 6 Web API new single program template usage

### ISSUE THREAD

**Issue by soroshsabz** [autofac/Autofac.Configuration#42]
ITNOA

## Problem Statement

I think README.md must be update for showing new usage of Configuration in .NET 6 new template

**Comment by tillig** [comment]
While we _might_ address this in [the ASP.NET integration documentation](https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html), or possibly add something to the Examples repo we have, this extension package is not specific to ASP.NET. The readme is only for this package, not intended to be a full replacement for our documentation site. There's also nothing special about using this inside ASP.NET that is different than using it outside ASP.NET, so there's not a lot of value to maintain every example of every possible combination of all the packages we maintain.

We're not adding ASP.NET specific usage to the README in this repo.

**Comment by soroshsabz** [comment]
I think we need exact documentation for Configuraiton in modern .NET (6,7,8),

**Comment by tillig** [comment]
The configuration works exactly the same today as it always has. That's not different in new .NET. You appear to be referring to how to integrate or use it in _specific application types_ (e.g., a web application) while you may be forgetting that this also can work in everything from console apps to background services. The point is that there isn't anything special for this to work in _any of these apps_ so there's not a lot of value in creating dozens of app types with every possible permutation of module available. "Where's the MAUI example with configuration? Where's the console app example that uses interceptors and configuration but not attribute metadata?" We have an examples repo and we have documentation - and that's why we link from the README to see more. We're not putting this right in the README. Sorry.
