### ISSUE TITLE
RegisterModule from configuration does not work in .NET 6 Web API

### ISSUE THREAD

**Issue by soroshsabz** [autofac/Autofac.Configuration#43]
ITNOA

## Describe the Bug

I am trying to add Autofac to a .Net 6.0 web API and read Autofac components configuration from `json` file.
I'm using the latest ASP.NET Core Web API template that generates a single start-up Program.cs file. But got a exception.

## Steps to Reproduce

Just in case of doubt, this is the entire content of the Program.cs file (yes, no namespaces or class definition. Only a Program.cs file and no StartUp class or Startup.cs file) 

```csharp
            var configurationBuilder = new ConfigurationBuilder();
            configurationBuilder.AddJsonFile("autofac.json");
            var autoFacConfigurationModule = new ConfigurationModule(configurationBuilder.Build());
            var temp = new IpTablesDotNetSystem();

            var builder = WebApplication.CreateBuilder(args);

            builder.Host.UseServiceProviderFactory(new AutofacServiceProviderFactory((containerBuilder) =>
            {
                containerBuilder.RegisterModule(autoFacConfigurationModule);
                //containerBuilder.RegisterType<IpTablesDotNetSystem>().As<IIpTablesSystem>().SingleInstance();
            }
            ));
            // Add services to the container.
            builder.Services.AddControllers();
            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();


            var app = builder.Build();

            // Configure the HTTP request pipeline.
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseAuthorization();


            app.MapControllers();

            app.Run();
```

But I got exception like below

As you can see in above code if I uncomment

```csharp
containerBuilder.RegisterType<IpTablesDotNetSystem>().As<IIpTablesSystem>().SingleInstance();
```

instead of `RegisterModule` all of project is correct working. but I need read configuration from files, and does not know how to do it?

## Expected Behavior

Work without any error

## Exception with Stack Trace

```text
System.InvalidOperationException: Unable to resolve service for type 'BSN.IpTables.Domain.IIpTablesSystem' while attempting to activate 'BSN.IpTables.Api.Controllers.HomeController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method364(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass7_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

## Dependency Versions

Installed Autofac versions:

    Autofac.Configuration (6.0.0)
    Autofac.Extensions.DependancyInjection (8.0.0)

Installed .Net 6.0 versions:

    Microsoft.AspNetCore.App 6.0.20
    Microsoft.NETCore.App 6.0.20

## Additional Info

I have a PR in https://github.com/BSVN/IpTables.Api/pull/9

**Comment by soroshsabz** [comment]
related to https://stackoverflow.com/q/76836609/1539100

**Comment by soroshsabz** [comment]
related to #42

**Comment by tillig** [comment]
1. Do not double-post. We monitor Stack Overflow and answer there if we can. The reason we point people there is that no one from the community monitors issues; and the Autofac maintainers are not paid folks, so if you want answers, we need to rely on the community.
2. We generally won't answer questions that aren't [minimal reproducible examples](https://stackoverflow.com/help/minimal-reproducible-example). While we'd love to help everyone, we aren't free consultants. There is a _lot_ of code in your example that has absolutely nothing to do with JSON configuration. There's Swagger, there's API endpoints, there's conditional code about the environment, there's no explanation of what this IP tables thing is, and **Autofac doesn't even show up in the stack trace**. All of that put together means you need someone who has time to help you simplify it, iterate over solutions, and drill in. That, unfortunately, isn't us. This isn't reproducible with any tools we have available because it's both _too much_ and _not enough_ all at the same time.

I'm happy to address more documentation and examples, so we'll leave those issues open, but I'm closing this one. It's not a bug, or at least not a bug that is provable in the format provided. If you figure it out and have something that we can absolutely reproduce that doesn't rely on your specific app code (e.g., whatever is in that custom IP tables thing) then feel free to open a new issue, including the stack trace where Autofac is failing to do something (not "the ASP.NET framework is failing to do something" or "Swagger is failing to do something") and we'll be happy to check it out.

**Comment by soroshsabz** [comment]
@tillig sorry for misbehave me, but I think autofac at least check schema of json files, and if any key is incorrect, throw exception

do you agree with me?

**Comment by tillig** [comment]
No. Autofac uses .NET Configuration under the covers. .NET Configuration is schema-less and can be merged with other configuration files/sources. We can throw if you specified a type that doesn't exist or something like that, but if you misspelled a configuration key... how do we know you didn't do that on purpose? How do we know you didn't just put your Autofac config in with the rest of your configuration? We don't. Just like ASP.NET doesn't throw if you have configuration keys it doesn't know about - it's _your configuration_. It's not a strongly-typed structure.

**Comment by soroshsabz** [comment]
I do not understand correctly, in `component` section of autofac configuration, why you cannot check all keys and schema? I do not think it is any conflict to using this configuration alongside of another configuration (like official .NET json configuration). we speak about specific part of configuration that exactly for autofac

For additional example, autofac does not check correct value for `instanceScope` that I think autofac can do it

**Comment by tillig** [comment]
Please understand that while you may have your registrations separated into a specific file, _you don't have to_. You know how you have `appsettings.json` in web apps? You could _put it all in there_. Right there, right alongside your logging configuration and everything else. It's _all just untyped configuration_. It sounds like you should spend some time digging into how .NET configuration works. [I wrote a pretty big article about it.](https://www.paraesthesia.com/archive/2018/06/20/microsoft-extensions-configuration-deep-dive/)

There are huge benefits to making this schema-free:

- I don't have to maintain a schema. This is a non-zero cost to develop, maintain, and support. That includes testing all the scenarios of "what happens if a person adds this but not this."
- I can extend the configuration syntax at will. It's always backwards-compatible.
- People can add _more stuff in_ like notes/comments, metadata fields that aren't for Autofac but might help (e.g., plugin titles or display info) and it won't cause Autofac config systems to explode.
- You're free to build this up by merging several configuration sources (JSON, XML, environment variables, INI files) to create a composite in whatever format you choose, as long as it ends up in .NET Configuration. You could add your own custom configuration source.

We used to have a strongly-typed XML configuration mechanism, many years ago, before .NET Core provided a standard configuration system. It was very painful to extend and work with. We're not going back to that.

If you would like to write your own JSON schema for validating your files, awesome. Do it. Since configuration can be provided in JSON, XML, INI, environment variables, from a database, from Azure App Configuration, or from any other source that .NET Configuration supports, I'm not interested in writing that or maintaining it. We also wouldn't accept a PR for it.

I'm sorry if that means you have to be more diligent in checking your configuration for typos or if you messed something up.

**All that said, we do already check for unrecognized values.** You specifically mentioned what happens if we see a bad value for `instanceScope`. [We have error handling for that already](https://github.com/autofac/Autofac.Configuration/blob/56e93b59ebc3c6f31754dc05dfe5f9a08f35649b/src/Autofac.Configuration/Core/ComponentRegistrar.cs#L564) and you should be getting an `InvalidOperationException` if you try using an invalid _value_. But if you misspell `instanceScope` and it's not found? That's not something we can check because _it's not required_.

Check through our registration code. You'll see we validate what we can, but no more. I'm sorry we won't be able to provide further assistance in this area. If you have a _very specific_ example that is not ASP.NET or web API specific, that we are not properly addressing, please file a new issue and include the configuration that isn't doing what you expect. Absolute minimal repro, no web code, just Autofac in a unit test format.

**Comment by soroshsabz** [comment]
thanks for details description :)
